version: '3'

services:
  app:
    container_name: 'blogs-api-app'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    container_name: 'database-blogs-api'
    image: postgres
    restart: always
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_PASSWORD=root
      - TZ=America/Sao_Paulo

